
DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS folders;

CREATE TABLE folders (
    folders_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folders_name TEXT NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);


CREATE TABLE notes (
    notes_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    notes_name TEXT NOT NULL,
    notes_content TEXT NOT NULL,
    folders_id INTEGER not null references folders,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);
